### PR TITLE
Update ScalaSocketIO.md

### PR DESCRIPTION
**Pull request by jkholodnov**
fixed typo

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jkholodnov,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by renatocaval** [comment]
CLA was not signed for this.

**Comment by jkholodnov** [comment]
Just signed the CLA, don't actually remember what this PR was for.

**Comment by renatocaval** [comment]
Thanks @jkholodnov.

**Pull request merged**
